packages:
  - apps/*
  - packages/*

catalog:
  typescript: 5.9.3
  zod: 4.3.6
  vitest: 4.0.18
  eslint: 9.39.2
  '@types/node': 26.1.1

allowBuilds:
  '@prisma/engines': true
  '@scarf/scarf': false
  argon2: true
  esbuild: true
  msgpackr-extract: false
  prisma: true
  protobufjs: true
  sharp: true
  unrs-resolver: true

overrides:
  '@hashgraph/sdk>protobufjs': 8.7.1
  '@hashgraph/proto>protobufjs': 8.7.1
  '@hashgraph/sdk>@grpc/grpc-js': 1.12.7
  '@nestjs/swagger>path-to-regexp': 8.4.2
  '@nestjs/config>lodash': 4.18.1
  '@nestjs/swagger>lodash': 4.18.1
  '@nestjs/swagger>js-yaml': 4.3.0
  'next>postcss': 8.5.10
  'bullmq>uuid': 11.1.1
  '@hono/node-server': 1.19.13
