packages:
  - apps/*
  - packages/*

catalog:
  typescript: 5.9.3
  zod: 4.3.6
  vitest: 4.0.18
  eslint: 9.39.2
  '@types/node': 24.10.1

allowBuilds:
  '@prisma/engines': true
  '@scarf/scarf': false
  argon2: true
  esbuild: true
  msgpackr-extract: false
  prisma: true
  protobufjs: true
  sharp: true
  unrs-resolver: true
